package com.yuen.domain;
// Generated Jan 30, 2018 8:45:22 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ContentCommentRelationship generated by hbm2java
 */
@Entity
@Table(name = "content_comment_relationship", catalog = "mycontact")
public class ContentCommentRelationship implements java.io.Serializable {

	private Integer contentCommentRelationshipId;
	private ContentComment contentCommentByParentContentCommentId;
	private ContentComment contentCommentByChildContentCommentId;

	public ContentCommentRelationship() {
	}

	public ContentCommentRelationship(ContentComment contentCommentByParentContentCommentId,
			ContentComment contentCommentByChildContentCommentId) {
		this.contentCommentByParentContentCommentId = contentCommentByParentContentCommentId;
		this.contentCommentByChildContentCommentId = contentCommentByChildContentCommentId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "content_comment_relationship_id", unique = true, nullable = false)
	public Integer getContentCommentRelationshipId() {
		return this.contentCommentRelationshipId;
	}

	public void setContentCommentRelationshipId(Integer contentCommentRelationshipId) {
		this.contentCommentRelationshipId = contentCommentRelationshipId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_content_comment_id")
	public ContentComment getContentCommentByParentContentCommentId() {
		return this.contentCommentByParentContentCommentId;
	}

	public void setContentCommentByParentContentCommentId(ContentComment contentCommentByParentContentCommentId) {
		this.contentCommentByParentContentCommentId = contentCommentByParentContentCommentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "child_content_comment_id")
	public ContentComment getContentCommentByChildContentCommentId() {
		return this.contentCommentByChildContentCommentId;
	}

	public void setContentCommentByChildContentCommentId(ContentComment contentCommentByChildContentCommentId) {
		this.contentCommentByChildContentCommentId = contentCommentByChildContentCommentId;
	}

}
