package com.yuen.domain;
// Generated Jan 30, 2018 8:45:22 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CoSoMap generated by hbm2java
 */
@Entity
@Table(name = "co_so_map", catalog = "mycontact")
public class CoSoMap implements java.io.Serializable {

	private Integer coSoId;
	private CoSoMapVersion coSoMapVersion;
	private CourseOutcome courseOutcome;
	private StudentOutcome studentOutcome;
	private char coSoLevel;

	public CoSoMap() {
	}

	public CoSoMap(char coSoLevel) {
		this.coSoLevel = coSoLevel;
	}

	public CoSoMap(CoSoMapVersion coSoMapVersion, CourseOutcome courseOutcome, StudentOutcome studentOutcome,
			char coSoLevel) {
		this.coSoMapVersion = coSoMapVersion;
		this.courseOutcome = courseOutcome;
		this.studentOutcome = studentOutcome;
		this.coSoLevel = coSoLevel;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "co_so_id", unique = true, nullable = false)
	public Integer getCoSoId() {
		return this.coSoId;
	}

	public void setCoSoId(Integer coSoId) {
		this.coSoId = coSoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "co_so_map_version_id")
	public CoSoMapVersion getCoSoMapVersion() {
		return this.coSoMapVersion;
	}

	public void setCoSoMapVersion(CoSoMapVersion coSoMapVersion) {
		this.coSoMapVersion = coSoMapVersion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "co_id")
	public CourseOutcome getCourseOutcome() {
		return this.courseOutcome;
	}

	public void setCourseOutcome(CourseOutcome courseOutcome) {
		this.courseOutcome = courseOutcome;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "so_id")
	public StudentOutcome getStudentOutcome() {
		return this.studentOutcome;
	}

	public void setStudentOutcome(StudentOutcome studentOutcome) {
		this.studentOutcome = studentOutcome;
	}

	@Column(name = "co_so_level", nullable = false, length = 1)
	public char getCoSoLevel() {
		return this.coSoLevel;
	}

	public void setCoSoLevel(char coSoLevel) {
		this.coSoLevel = coSoLevel;
	}

}
