package com.yuen.domain;
// Generated Jan 30, 2018 8:45:22 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CourseRelationshipType generated by hbm2java
 */
@Entity
@Table(name = "course_relationship_type", catalog = "mycontact")
public class CourseRelationshipType implements java.io.Serializable {

	private Integer courseRelationshipTypeId;
	private String courseRelationshipTypeCode;
	private String courseRelationshipTypeDesc;
	private Set<CourseRelationship> courseRelationships = new HashSet<CourseRelationship>(0);

	public CourseRelationshipType() {
	}

	public CourseRelationshipType(String courseRelationshipTypeCode, String courseRelationshipTypeDesc) {
		this.courseRelationshipTypeCode = courseRelationshipTypeCode;
		this.courseRelationshipTypeDesc = courseRelationshipTypeDesc;
	}

	public CourseRelationshipType(String courseRelationshipTypeCode, String courseRelationshipTypeDesc,
			Set<CourseRelationship> courseRelationships) {
		this.courseRelationshipTypeCode = courseRelationshipTypeCode;
		this.courseRelationshipTypeDesc = courseRelationshipTypeDesc;
		this.courseRelationships = courseRelationships;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "course_relationship_type_id", unique = true, nullable = false)
	public Integer getCourseRelationshipTypeId() {
		return this.courseRelationshipTypeId;
	}

	public void setCourseRelationshipTypeId(Integer courseRelationshipTypeId) {
		this.courseRelationshipTypeId = courseRelationshipTypeId;
	}

	@Column(name = "course_relationship_type_code", nullable = false, length = 100)
	public String getCourseRelationshipTypeCode() {
		return this.courseRelationshipTypeCode;
	}

	public void setCourseRelationshipTypeCode(String courseRelationshipTypeCode) {
		this.courseRelationshipTypeCode = courseRelationshipTypeCode;
	}

	@Column(name = "course_relationship_type_desc", nullable = false, length = 65535)
	public String getCourseRelationshipTypeDesc() {
		return this.courseRelationshipTypeDesc;
	}

	public void setCourseRelationshipTypeDesc(String courseRelationshipTypeDesc) {
		this.courseRelationshipTypeDesc = courseRelationshipTypeDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "courseRelationshipType")
	public Set<CourseRelationship> getCourseRelationships() {
		return this.courseRelationships;
	}

	public void setCourseRelationships(Set<CourseRelationship> courseRelationships) {
		this.courseRelationships = courseRelationships;
	}

}
