package com.yuen.domain;
// Generated Jan 30, 2018 8:45:22 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CourseCommentRelationship generated by hbm2java
 */
@Entity
@Table(name = "course_comment_relationship", catalog = "mycontact")
public class CourseCommentRelationship implements java.io.Serializable {

	private Integer courseCommentRelationshipId;
	private CourseComment courseCommentByChildCourseCommentId;
	private CourseComment courseCommentByParentCourseCommentId;

	public CourseCommentRelationship() {
	}

	public CourseCommentRelationship(CourseComment courseCommentByChildCourseCommentId,
			CourseComment courseCommentByParentCourseCommentId) {
		this.courseCommentByChildCourseCommentId = courseCommentByChildCourseCommentId;
		this.courseCommentByParentCourseCommentId = courseCommentByParentCourseCommentId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "course_comment_relationship_id", unique = true, nullable = false)
	public Integer getCourseCommentRelationshipId() {
		return this.courseCommentRelationshipId;
	}

	public void setCourseCommentRelationshipId(Integer courseCommentRelationshipId) {
		this.courseCommentRelationshipId = courseCommentRelationshipId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "child_course_comment_id")
	public CourseComment getCourseCommentByChildCourseCommentId() {
		return this.courseCommentByChildCourseCommentId;
	}

	public void setCourseCommentByChildCourseCommentId(CourseComment courseCommentByChildCourseCommentId) {
		this.courseCommentByChildCourseCommentId = courseCommentByChildCourseCommentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_course_comment_id")
	public CourseComment getCourseCommentByParentCourseCommentId() {
		return this.courseCommentByParentCourseCommentId;
	}

	public void setCourseCommentByParentCourseCommentId(CourseComment courseCommentByParentCourseCommentId) {
		this.courseCommentByParentCourseCommentId = courseCommentByParentCourseCommentId;
	}

}
