package com.yuen.domain;
// Generated Jan 30, 2018 8:45:22 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FillableElement generated by hbm2java
 */
@Entity
@Table(name = "fillable_element", catalog = "mycontact")
public class FillableElement implements java.io.Serializable {

	private Integer fillableElementId;
	private QuestionItem questionItem;
	private String fillableElementCode;
	private String fillableElementHint;
	private String fillableElementSolution;
	private String fillableElementAnswer;
	private Byte fillableElementOrder;
	private Set<FilledElement> filledElements = new HashSet<FilledElement>(0);

	public FillableElement() {
	}

	public FillableElement(String fillableElementHint) {
		this.fillableElementHint = fillableElementHint;
	}

	public FillableElement(QuestionItem questionItem, String fillableElementCode, String fillableElementHint,
			String fillableElementSolution, String fillableElementAnswer, Byte fillableElementOrder,
			Set<FilledElement> filledElements) {
		this.questionItem = questionItem;
		this.fillableElementCode = fillableElementCode;
		this.fillableElementHint = fillableElementHint;
		this.fillableElementSolution = fillableElementSolution;
		this.fillableElementAnswer = fillableElementAnswer;
		this.fillableElementOrder = fillableElementOrder;
		this.filledElements = filledElements;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "fillable_element_id", unique = true, nullable = false)
	public Integer getFillableElementId() {
		return this.fillableElementId;
	}

	public void setFillableElementId(Integer fillableElementId) {
		this.fillableElementId = fillableElementId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id")
	public QuestionItem getQuestionItem() {
		return this.questionItem;
	}

	public void setQuestionItem(QuestionItem questionItem) {
		this.questionItem = questionItem;
	}

	@Column(name = "fillable_element_code", length = 10)
	public String getFillableElementCode() {
		return this.fillableElementCode;
	}

	public void setFillableElementCode(String fillableElementCode) {
		this.fillableElementCode = fillableElementCode;
	}

	@Column(name = "fillable_element_hint", nullable = false, length = 65535)
	public String getFillableElementHint() {
		return this.fillableElementHint;
	}

	public void setFillableElementHint(String fillableElementHint) {
		this.fillableElementHint = fillableElementHint;
	}

	@Column(name = "fillable_element_solution", length = 65535)
	public String getFillableElementSolution() {
		return this.fillableElementSolution;
	}

	public void setFillableElementSolution(String fillableElementSolution) {
		this.fillableElementSolution = fillableElementSolution;
	}

	@Column(name = "fillable_element_answer", length = 65535)
	public String getFillableElementAnswer() {
		return this.fillableElementAnswer;
	}

	public void setFillableElementAnswer(String fillableElementAnswer) {
		this.fillableElementAnswer = fillableElementAnswer;
	}

	@Column(name = "fillable_element_order")
	public Byte getFillableElementOrder() {
		return this.fillableElementOrder;
	}

	public void setFillableElementOrder(Byte fillableElementOrder) {
		this.fillableElementOrder = fillableElementOrder;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fillableElement")
	public Set<FilledElement> getFilledElements() {
		return this.filledElements;
	}

	public void setFilledElements(Set<FilledElement> filledElements) {
		this.filledElements = filledElements;
	}

}
