package com.yuen.domain;
// Generated Jan 30, 2018 8:45:22 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FilledElement generated by hbm2java
 */
@Entity
@Table(name = "filled_element", catalog = "mycontact")
public class FilledElement implements java.io.Serializable {

	private Integer filledElementId;
	private FillableElement fillableElement;
	private TakerSolution takerSolution;
	private String filledElementValue;

	public FilledElement() {
	}

	public FilledElement(String filledElementValue) {
		this.filledElementValue = filledElementValue;
	}

	public FilledElement(FillableElement fillableElement, TakerSolution takerSolution, String filledElementValue) {
		this.fillableElement = fillableElement;
		this.takerSolution = takerSolution;
		this.filledElementValue = filledElementValue;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "filled_element_id", unique = true, nullable = false)
	public Integer getFilledElementId() {
		return this.filledElementId;
	}

	public void setFilledElementId(Integer filledElementId) {
		this.filledElementId = filledElementId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fillable_element_id")
	public FillableElement getFillableElement() {
		return this.fillableElement;
	}

	public void setFillableElement(FillableElement fillableElement) {
		this.fillableElement = fillableElement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "taker_solution_id")
	public TakerSolution getTakerSolution() {
		return this.takerSolution;
	}

	public void setTakerSolution(TakerSolution takerSolution) {
		this.takerSolution = takerSolution;
	}

	@Column(name = "filled_element_value", nullable = false, length = 65535)
	public String getFilledElementValue() {
		return this.filledElementValue;
	}

	public void setFilledElementValue(String filledElementValue) {
		this.filledElementValue = filledElementValue;
	}

}
