package com.yuen.domain;
// Generated Jan 30, 2018 8:45:22 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PeoCommentRelationship generated by hbm2java
 */
@Entity
@Table(name = "peo_comment_relationship", catalog = "mycontact")
public class PeoCommentRelationship implements java.io.Serializable {

	private Integer peoCommentRelationshipId;
	private PeoComment peoCommentByChildPeoCommentId;
	private PeoComment peoCommentByParentPeoCommentId;
	private String peoCommentRelationshipDesc;

	public PeoCommentRelationship() {
	}

	public PeoCommentRelationship(PeoComment peoCommentByChildPeoCommentId, PeoComment peoCommentByParentPeoCommentId,
			String peoCommentRelationshipDesc) {
		this.peoCommentByChildPeoCommentId = peoCommentByChildPeoCommentId;
		this.peoCommentByParentPeoCommentId = peoCommentByParentPeoCommentId;
		this.peoCommentRelationshipDesc = peoCommentRelationshipDesc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "peo_comment_relationship_id", unique = true, nullable = false)
	public Integer getPeoCommentRelationshipId() {
		return this.peoCommentRelationshipId;
	}

	public void setPeoCommentRelationshipId(Integer peoCommentRelationshipId) {
		this.peoCommentRelationshipId = peoCommentRelationshipId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "child_peo_comment_id")
	public PeoComment getPeoCommentByChildPeoCommentId() {
		return this.peoCommentByChildPeoCommentId;
	}

	public void setPeoCommentByChildPeoCommentId(PeoComment peoCommentByChildPeoCommentId) {
		this.peoCommentByChildPeoCommentId = peoCommentByChildPeoCommentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_peo_comment_id")
	public PeoComment getPeoCommentByParentPeoCommentId() {
		return this.peoCommentByParentPeoCommentId;
	}

	public void setPeoCommentByParentPeoCommentId(PeoComment peoCommentByParentPeoCommentId) {
		this.peoCommentByParentPeoCommentId = peoCommentByParentPeoCommentId;
	}

	@Column(name = "peo_comment_relationship_desc", length = 65535)
	public String getPeoCommentRelationshipDesc() {
		return this.peoCommentRelationshipDesc;
	}

	public void setPeoCommentRelationshipDesc(String peoCommentRelationshipDesc) {
		this.peoCommentRelationshipDesc = peoCommentRelationshipDesc;
	}

}
