package com.yuen.domain;
// Generated Jan 30, 2018 8:45:22 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PeoSoMap generated by hbm2java
 */
@Entity
@Table(name = "peo_so_map", catalog = "mycontact")
public class PeoSoMap implements java.io.Serializable {

	private Integer peoSoId;
	private Peo peo;
	private PeoSoMapVersion peoSoMapVersion;
	private StudentOutcome studentOutcome;

	public PeoSoMap() {
	}

	public PeoSoMap(Peo peo, PeoSoMapVersion peoSoMapVersion, StudentOutcome studentOutcome) {
		this.peo = peo;
		this.peoSoMapVersion = peoSoMapVersion;
		this.studentOutcome = studentOutcome;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "peo_so_id", unique = true, nullable = false)
	public Integer getPeoSoId() {
		return this.peoSoId;
	}

	public void setPeoSoId(Integer peoSoId) {
		this.peoSoId = peoSoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "peo_id")
	public Peo getPeo() {
		return this.peo;
	}

	public void setPeo(Peo peo) {
		this.peo = peo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "peo_so_map_version_id")
	public PeoSoMapVersion getPeoSoMapVersion() {
		return this.peoSoMapVersion;
	}

	public void setPeoSoMapVersion(PeoSoMapVersion peoSoMapVersion) {
		this.peoSoMapVersion = peoSoMapVersion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "so_id")
	public StudentOutcome getStudentOutcome() {
		return this.studentOutcome;
	}

	public void setStudentOutcome(StudentOutcome studentOutcome) {
		this.studentOutcome = studentOutcome;
	}

}
