package com.yuen.domain;
// Generated Jan 30, 2018 8:45:22 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PeoSoMapVersion generated by hbm2java
 */
@Entity
@Table(name = "peo_so_map_version", catalog = "mycontact")
public class PeoSoMapVersion implements java.io.Serializable {

	private Integer peoSoMapVersionId;
	private PeoVersion peoVersion;
	private StudentOutcomeVersion studentOutcomeVersion;
	private int peoSoMapVersionCode;
	private Date peoSoMapVersionDate;
	private boolean peoSoMapVersionIsused;
	private Set<PeoSoMap> peoSoMaps = new HashSet<PeoSoMap>(0);

	public PeoSoMapVersion() {
	}

	public PeoSoMapVersion(int peoSoMapVersionCode, boolean peoSoMapVersionIsused) {
		this.peoSoMapVersionCode = peoSoMapVersionCode;
		this.peoSoMapVersionIsused = peoSoMapVersionIsused;
	}

	public PeoSoMapVersion(PeoVersion peoVersion, StudentOutcomeVersion studentOutcomeVersion, int peoSoMapVersionCode,
			Date peoSoMapVersionDate, boolean peoSoMapVersionIsused, Set<PeoSoMap> peoSoMaps) {
		this.peoVersion = peoVersion;
		this.studentOutcomeVersion = studentOutcomeVersion;
		this.peoSoMapVersionCode = peoSoMapVersionCode;
		this.peoSoMapVersionDate = peoSoMapVersionDate;
		this.peoSoMapVersionIsused = peoSoMapVersionIsused;
		this.peoSoMaps = peoSoMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "peo_so_map_version_id", unique = true, nullable = false)
	public Integer getPeoSoMapVersionId() {
		return this.peoSoMapVersionId;
	}

	public void setPeoSoMapVersionId(Integer peoSoMapVersionId) {
		this.peoSoMapVersionId = peoSoMapVersionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "peo_version_id")
	public PeoVersion getPeoVersion() {
		return this.peoVersion;
	}

	public void setPeoVersion(PeoVersion peoVersion) {
		this.peoVersion = peoVersion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_outcome_version_id")
	public StudentOutcomeVersion getStudentOutcomeVersion() {
		return this.studentOutcomeVersion;
	}

	public void setStudentOutcomeVersion(StudentOutcomeVersion studentOutcomeVersion) {
		this.studentOutcomeVersion = studentOutcomeVersion;
	}

	@Column(name = "peo_so_map_version_code", nullable = false)
	public int getPeoSoMapVersionCode() {
		return this.peoSoMapVersionCode;
	}

	public void setPeoSoMapVersionCode(int peoSoMapVersionCode) {
		this.peoSoMapVersionCode = peoSoMapVersionCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "peo_so_map_version_date", length = 10)
	public Date getPeoSoMapVersionDate() {
		return this.peoSoMapVersionDate;
	}

	public void setPeoSoMapVersionDate(Date peoSoMapVersionDate) {
		this.peoSoMapVersionDate = peoSoMapVersionDate;
	}

	@Column(name = "peo_so_map_version_isused", nullable = false)
	public boolean isPeoSoMapVersionIsused() {
		return this.peoSoMapVersionIsused;
	}

	public void setPeoSoMapVersionIsused(boolean peoSoMapVersionIsused) {
		this.peoSoMapVersionIsused = peoSoMapVersionIsused;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "peoSoMapVersion")
	public Set<PeoSoMap> getPeoSoMaps() {
		return this.peoSoMaps;
	}

	public void setPeoSoMaps(Set<PeoSoMap> peoSoMaps) {
		this.peoSoMaps = peoSoMaps;
	}

}
