package com.yuen.domain;
// Generated Jan 30, 2018 8:45:22 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PeoVersion generated by hbm2java
 */
@Entity
@Table(name = "peo_version", catalog = "mycontact")
public class PeoVersion implements java.io.Serializable {

	private Integer peoVersionId;
	private EducationalProgram educationalProgram;
	private String peoVersionCode;
	private Date peoVersionDate;
	private boolean peoVersionIsused;
	private Set<PeoMissionMapVersion> peoMissionMapVersions = new HashSet<PeoMissionMapVersion>(0);
	private Set<PeoSoMapVersion> peoSoMapVersions = new HashSet<PeoSoMapVersion>(0);
	private Set<Peo> peos = new HashSet<Peo>(0);

	public PeoVersion() {
	}

	public PeoVersion(String peoVersionCode, Date peoVersionDate, boolean peoVersionIsused) {
		this.peoVersionCode = peoVersionCode;
		this.peoVersionDate = peoVersionDate;
		this.peoVersionIsused = peoVersionIsused;
	}

	public PeoVersion(EducationalProgram educationalProgram, String peoVersionCode, Date peoVersionDate,
			boolean peoVersionIsused, Set<PeoMissionMapVersion> peoMissionMapVersions,
			Set<PeoSoMapVersion> peoSoMapVersions, Set<Peo> peos) {
		this.educationalProgram = educationalProgram;
		this.peoVersionCode = peoVersionCode;
		this.peoVersionDate = peoVersionDate;
		this.peoVersionIsused = peoVersionIsused;
		this.peoMissionMapVersions = peoMissionMapVersions;
		this.peoSoMapVersions = peoSoMapVersions;
		this.peos = peos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "peo_version_id", unique = true, nullable = false)
	public Integer getPeoVersionId() {
		return this.peoVersionId;
	}

	public void setPeoVersionId(Integer peoVersionId) {
		this.peoVersionId = peoVersionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "edu_program_id")
	public EducationalProgram getEducationalProgram() {
		return this.educationalProgram;
	}

	public void setEducationalProgram(EducationalProgram educationalProgram) {
		this.educationalProgram = educationalProgram;
	}

	@Column(name = "peo_version_code", nullable = false, length = 10)
	public String getPeoVersionCode() {
		return this.peoVersionCode;
	}

	public void setPeoVersionCode(String peoVersionCode) {
		this.peoVersionCode = peoVersionCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "peo_version_date", nullable = false, length = 10)
	public Date getPeoVersionDate() {
		return this.peoVersionDate;
	}

	public void setPeoVersionDate(Date peoVersionDate) {
		this.peoVersionDate = peoVersionDate;
	}

	@Column(name = "peo_version_isused", nullable = false)
	public boolean isPeoVersionIsused() {
		return this.peoVersionIsused;
	}

	public void setPeoVersionIsused(boolean peoVersionIsused) {
		this.peoVersionIsused = peoVersionIsused;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "peoVersion")
	public Set<PeoMissionMapVersion> getPeoMissionMapVersions() {
		return this.peoMissionMapVersions;
	}

	public void setPeoMissionMapVersions(Set<PeoMissionMapVersion> peoMissionMapVersions) {
		this.peoMissionMapVersions = peoMissionMapVersions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "peoVersion")
	public Set<PeoSoMapVersion> getPeoSoMapVersions() {
		return this.peoSoMapVersions;
	}

	public void setPeoSoMapVersions(Set<PeoSoMapVersion> peoSoMapVersions) {
		this.peoSoMapVersions = peoSoMapVersions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "peoVersion")
	public Set<Peo> getPeos() {
		return this.peos;
	}

	public void setPeos(Set<Peo> peos) {
		this.peos = peos;
	}

}
