package com.yuen.domain;
// Generated Jan 30, 2018 8:45:22 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerformanceIndicator generated by hbm2java
 */
@Entity
@Table(name = "performance_indicator", catalog = "mycontact")
public class PerformanceIndicator implements java.io.Serializable {

	private Integer piId;
	private PerformanceIndicatorVersion performanceIndicatorVersion;
	private String piDesc;
	private Date piIntroducedDate;
	private boolean piUsed;
	private Integer piVersion;

	public PerformanceIndicator() {
	}

	public PerformanceIndicator(String piDesc, Date piIntroducedDate, boolean piUsed) {
		this.piDesc = piDesc;
		this.piIntroducedDate = piIntroducedDate;
		this.piUsed = piUsed;
	}

	public PerformanceIndicator(PerformanceIndicatorVersion performanceIndicatorVersion, String piDesc,
			Date piIntroducedDate, boolean piUsed, Integer piVersion) {
		this.performanceIndicatorVersion = performanceIndicatorVersion;
		this.piDesc = piDesc;
		this.piIntroducedDate = piIntroducedDate;
		this.piUsed = piUsed;
		this.piVersion = piVersion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "pi_id", unique = true, nullable = false)
	public Integer getPiId() {
		return this.piId;
	}

	public void setPiId(Integer piId) {
		this.piId = piId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "performance_indicator_version_id")
	public PerformanceIndicatorVersion getPerformanceIndicatorVersion() {
		return this.performanceIndicatorVersion;
	}

	public void setPerformanceIndicatorVersion(PerformanceIndicatorVersion performanceIndicatorVersion) {
		this.performanceIndicatorVersion = performanceIndicatorVersion;
	}

	@Column(name = "pi_desc", nullable = false, length = 65535)
	public String getPiDesc() {
		return this.piDesc;
	}

	public void setPiDesc(String piDesc) {
		this.piDesc = piDesc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "pi_introduced_date", nullable = false, length = 10)
	public Date getPiIntroducedDate() {
		return this.piIntroducedDate;
	}

	public void setPiIntroducedDate(Date piIntroducedDate) {
		this.piIntroducedDate = piIntroducedDate;
	}

	@Column(name = "pi_used", nullable = false)
	public boolean isPiUsed() {
		return this.piUsed;
	}

	public void setPiUsed(boolean piUsed) {
		this.piUsed = piUsed;
	}

	@Column(name = "pi_version")
	public Integer getPiVersion() {
		return this.piVersion;
	}

	public void setPiVersion(Integer piVersion) {
		this.piVersion = piVersion;
	}

}
