package com.yuen.domain;
// Generated Jan 30, 2018 8:45:22 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Previledge generated by hbm2java
 */
@Entity
@Table(name = "previledge", catalog = "mycontact")
public class Previledge implements java.io.Serializable {

	private Integer previledgeId;
	private String previledgeCode;
	private String previledgeDesc;
	private Set<CourseAccessMode> courseAccessModes = new HashSet<CourseAccessMode>(0);
	private Set<RolePreviledgeMap> rolePreviledgeMaps = new HashSet<RolePreviledgeMap>(0);
	private Set<QuestionAccessMode> questionAccessModes = new HashSet<QuestionAccessMode>(0);
	private Set<TestAccessMode> testAccessModes = new HashSet<TestAccessMode>(0);
	private Set<PreviledgeRelstionship> previledgeRelstionshipsForParentPreviledgeId = new HashSet<PreviledgeRelstionship>(
			0);
	private Set<TopicAccessMode> topicAccessModes = new HashSet<TopicAccessMode>(0);
	private Set<PreviledgeRelstionship> previledgeRelstionshipsForChildPreviledgeId = new HashSet<PreviledgeRelstionship>(
			0);
	private Set<ProgramAccessMode> programAccessModes = new HashSet<ProgramAccessMode>(0);

	public Previledge() {
	}

	public Previledge(String previledgeCode, String previledgeDesc) {
		this.previledgeCode = previledgeCode;
		this.previledgeDesc = previledgeDesc;
	}

	public Previledge(String previledgeCode, String previledgeDesc, Set<CourseAccessMode> courseAccessModes,
			Set<RolePreviledgeMap> rolePreviledgeMaps, Set<QuestionAccessMode> questionAccessModes,
			Set<TestAccessMode> testAccessModes,
			Set<PreviledgeRelstionship> previledgeRelstionshipsForParentPreviledgeId,
			Set<TopicAccessMode> topicAccessModes,
			Set<PreviledgeRelstionship> previledgeRelstionshipsForChildPreviledgeId,
			Set<ProgramAccessMode> programAccessModes) {
		this.previledgeCode = previledgeCode;
		this.previledgeDesc = previledgeDesc;
		this.courseAccessModes = courseAccessModes;
		this.rolePreviledgeMaps = rolePreviledgeMaps;
		this.questionAccessModes = questionAccessModes;
		this.testAccessModes = testAccessModes;
		this.previledgeRelstionshipsForParentPreviledgeId = previledgeRelstionshipsForParentPreviledgeId;
		this.topicAccessModes = topicAccessModes;
		this.previledgeRelstionshipsForChildPreviledgeId = previledgeRelstionshipsForChildPreviledgeId;
		this.programAccessModes = programAccessModes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "previledge_id", unique = true, nullable = false)
	public Integer getPreviledgeId() {
		return this.previledgeId;
	}

	public void setPreviledgeId(Integer previledgeId) {
		this.previledgeId = previledgeId;
	}

	@Column(name = "previledge_code", nullable = false, length = 100)
	public String getPreviledgeCode() {
		return this.previledgeCode;
	}

	public void setPreviledgeCode(String previledgeCode) {
		this.previledgeCode = previledgeCode;
	}

	@Column(name = "previledge_desc", nullable = false, length = 65535)
	public String getPreviledgeDesc() {
		return this.previledgeDesc;
	}

	public void setPreviledgeDesc(String previledgeDesc) {
		this.previledgeDesc = previledgeDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "previledge")
	public Set<CourseAccessMode> getCourseAccessModes() {
		return this.courseAccessModes;
	}

	public void setCourseAccessModes(Set<CourseAccessMode> courseAccessModes) {
		this.courseAccessModes = courseAccessModes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "previledge")
	public Set<RolePreviledgeMap> getRolePreviledgeMaps() {
		return this.rolePreviledgeMaps;
	}

	public void setRolePreviledgeMaps(Set<RolePreviledgeMap> rolePreviledgeMaps) {
		this.rolePreviledgeMaps = rolePreviledgeMaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "previledge")
	public Set<QuestionAccessMode> getQuestionAccessModes() {
		return this.questionAccessModes;
	}

	public void setQuestionAccessModes(Set<QuestionAccessMode> questionAccessModes) {
		this.questionAccessModes = questionAccessModes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "previledge")
	public Set<TestAccessMode> getTestAccessModes() {
		return this.testAccessModes;
	}

	public void setTestAccessModes(Set<TestAccessMode> testAccessModes) {
		this.testAccessModes = testAccessModes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "previledgeByParentPreviledgeId")
	public Set<PreviledgeRelstionship> getPreviledgeRelstionshipsForParentPreviledgeId() {
		return this.previledgeRelstionshipsForParentPreviledgeId;
	}

	public void setPreviledgeRelstionshipsForParentPreviledgeId(
			Set<PreviledgeRelstionship> previledgeRelstionshipsForParentPreviledgeId) {
		this.previledgeRelstionshipsForParentPreviledgeId = previledgeRelstionshipsForParentPreviledgeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "previledge")
	public Set<TopicAccessMode> getTopicAccessModes() {
		return this.topicAccessModes;
	}

	public void setTopicAccessModes(Set<TopicAccessMode> topicAccessModes) {
		this.topicAccessModes = topicAccessModes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "previledgeByChildPreviledgeId")
	public Set<PreviledgeRelstionship> getPreviledgeRelstionshipsForChildPreviledgeId() {
		return this.previledgeRelstionshipsForChildPreviledgeId;
	}

	public void setPreviledgeRelstionshipsForChildPreviledgeId(
			Set<PreviledgeRelstionship> previledgeRelstionshipsForChildPreviledgeId) {
		this.previledgeRelstionshipsForChildPreviledgeId = previledgeRelstionshipsForChildPreviledgeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "previledge")
	public Set<ProgramAccessMode> getProgramAccessModes() {
		return this.programAccessModes;
	}

	public void setProgramAccessModes(Set<ProgramAccessMode> programAccessModes) {
		this.programAccessModes = programAccessModes;
	}

}
