package com.yuen.domain;
// Generated Jan 30, 2018 8:45:22 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProgramDecision generated by hbm2java
 */
@Entity
@Table(name = "program_decision", catalog = "mycontact")
public class ProgramDecision implements java.io.Serializable {

	private Integer programDecisionId;
	private String programDecisionCode;
	private String programDecisionDesc;
	private Set<ProgramComment> programComments = new HashSet<ProgramComment>(0);
	private Set<PeoComment> peoComments = new HashSet<PeoComment>(0);
	private Set<SoComment> soComments = new HashSet<SoComment>(0);

	public ProgramDecision() {
	}

	public ProgramDecision(String programDecisionCode, String programDecisionDesc) {
		this.programDecisionCode = programDecisionCode;
		this.programDecisionDesc = programDecisionDesc;
	}

	public ProgramDecision(String programDecisionCode, String programDecisionDesc, Set<ProgramComment> programComments,
			Set<PeoComment> peoComments, Set<SoComment> soComments) {
		this.programDecisionCode = programDecisionCode;
		this.programDecisionDesc = programDecisionDesc;
		this.programComments = programComments;
		this.peoComments = peoComments;
		this.soComments = soComments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "program_decision_id", unique = true, nullable = false)
	public Integer getProgramDecisionId() {
		return this.programDecisionId;
	}

	public void setProgramDecisionId(Integer programDecisionId) {
		this.programDecisionId = programDecisionId;
	}

	@Column(name = "program_decision_code", nullable = false, length = 100)
	public String getProgramDecisionCode() {
		return this.programDecisionCode;
	}

	public void setProgramDecisionCode(String programDecisionCode) {
		this.programDecisionCode = programDecisionCode;
	}

	@Column(name = "program_decision_desc", nullable = false, length = 65535)
	public String getProgramDecisionDesc() {
		return this.programDecisionDesc;
	}

	public void setProgramDecisionDesc(String programDecisionDesc) {
		this.programDecisionDesc = programDecisionDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "programDecision")
	public Set<ProgramComment> getProgramComments() {
		return this.programComments;
	}

	public void setProgramComments(Set<ProgramComment> programComments) {
		this.programComments = programComments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "programDecision")
	public Set<PeoComment> getPeoComments() {
		return this.peoComments;
	}

	public void setPeoComments(Set<PeoComment> peoComments) {
		this.peoComments = peoComments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "programDecision")
	public Set<SoComment> getSoComments() {
		return this.soComments;
	}

	public void setSoComments(Set<SoComment> soComments) {
		this.soComments = soComments;
	}

}
