package com.yuen.domain;
// Generated Jan 30, 2018 8:45:22 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProgramCourseMapping generated by hbm2java
 */
@Entity
@Table(name = "program_course_mapping", catalog = "mycontact")
public class ProgramCourseMapping implements java.io.Serializable {

	private Integer programCourseId;
	private Course course;
	private CourseRequiredLevel courseRequiredLevel;
	private EducationalProgram educationalProgram;
	private byte programCourseTimeIndex;

	public ProgramCourseMapping() {
	}

	public ProgramCourseMapping(byte programCourseTimeIndex) {
		this.programCourseTimeIndex = programCourseTimeIndex;
	}

	public ProgramCourseMapping(Course course, CourseRequiredLevel courseRequiredLevel,
			EducationalProgram educationalProgram, byte programCourseTimeIndex) {
		this.course = course;
		this.courseRequiredLevel = courseRequiredLevel;
		this.educationalProgram = educationalProgram;
		this.programCourseTimeIndex = programCourseTimeIndex;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "program_course_id", unique = true, nullable = false)
	public Integer getProgramCourseId() {
		return this.programCourseId;
	}

	public void setProgramCourseId(Integer programCourseId) {
		this.programCourseId = programCourseId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "course_id")
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "course_required_level_id")
	public CourseRequiredLevel getCourseRequiredLevel() {
		return this.courseRequiredLevel;
	}

	public void setCourseRequiredLevel(CourseRequiredLevel courseRequiredLevel) {
		this.courseRequiredLevel = courseRequiredLevel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "edu_program_id")
	public EducationalProgram getEducationalProgram() {
		return this.educationalProgram;
	}

	public void setEducationalProgram(EducationalProgram educationalProgram) {
		this.educationalProgram = educationalProgram;
	}

	@Column(name = "program_course_time_index", nullable = false)
	public byte getProgramCourseTimeIndex() {
		return this.programCourseTimeIndex;
	}

	public void setProgramCourseTimeIndex(byte programCourseTimeIndex) {
		this.programCourseTimeIndex = programCourseTimeIndex;
	}

}
