package com.yuen.domain;
// Generated Jan 30, 2018 8:45:22 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QgroupContentMap generated by hbm2java
 */
@Entity
@Table(name = "qgroup_content_map", catalog = "mycontact")
public class QgroupContentMap implements java.io.Serializable {

	private Integer qgroupContentMapId;
	private CourseContent courseContent;
	private QuestionGroup questionGroup;

	public QgroupContentMap() {
	}

	public QgroupContentMap(CourseContent courseContent, QuestionGroup questionGroup) {
		this.courseContent = courseContent;
		this.questionGroup = questionGroup;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "qgroup_content_map_id", unique = true, nullable = false)
	public Integer getQgroupContentMapId() {
		return this.qgroupContentMapId;
	}

	public void setQgroupContentMapId(Integer qgroupContentMapId) {
		this.qgroupContentMapId = qgroupContentMapId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "course_content_id")
	public CourseContent getCourseContent() {
		return this.courseContent;
	}

	public void setCourseContent(CourseContent courseContent) {
		this.courseContent = courseContent;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "question_group_id")
	public QuestionGroup getQuestionGroup() {
		return this.questionGroup;
	}

	public void setQuestionGroup(QuestionGroup questionGroup) {
		this.questionGroup = questionGroup;
	}

}
