package com.yuen.domain;
// Generated Jan 30, 2018 8:45:22 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QgroupTopicMap generated by hbm2java
 */
@Entity
@Table(name = "qgroup_topic_map", catalog = "mycontact")
public class QgroupTopicMap implements java.io.Serializable {

	private Integer qgroupTopicMapId;
	private QuestionGroup questionGroup;
	private Topic topic;

	public QgroupTopicMap() {
	}

	public QgroupTopicMap(QuestionGroup questionGroup, Topic topic) {
		this.questionGroup = questionGroup;
		this.topic = topic;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "qgroup_topic_map_id", unique = true, nullable = false)
	public Integer getQgroupTopicMapId() {
		return this.qgroupTopicMapId;
	}

	public void setQgroupTopicMapId(Integer qgroupTopicMapId) {
		this.qgroupTopicMapId = qgroupTopicMapId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "question_group_id")
	public QuestionGroup getQuestionGroup() {
		return this.questionGroup;
	}

	public void setQuestionGroup(QuestionGroup questionGroup) {
		this.questionGroup = questionGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "topic_id")
	public Topic getTopic() {
		return this.topic;
	}

	public void setTopic(Topic topic) {
		this.topic = topic;
	}

}
