package com.yuen.domain;
// Generated Jan 30, 2018 8:45:22 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QuestionInfo generated by hbm2java
 */
@Entity
@Table(name = "question_info", catalog = "mycontact")
public class QuestionInfo implements java.io.Serializable {

	private Integer questionInfoId;
	private Question question;
	private String questionInfoProp;
	private String questionInfoValue;
	private String questionInfoDesc;

	public QuestionInfo() {
	}

	public QuestionInfo(String questionInfoProp, String questionInfoValue) {
		this.questionInfoProp = questionInfoProp;
		this.questionInfoValue = questionInfoValue;
	}

	public QuestionInfo(Question question, String questionInfoProp, String questionInfoValue, String questionInfoDesc) {
		this.question = question;
		this.questionInfoProp = questionInfoProp;
		this.questionInfoValue = questionInfoValue;
		this.questionInfoDesc = questionInfoDesc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "question_info_id", unique = true, nullable = false)
	public Integer getQuestionInfoId() {
		return this.questionInfoId;
	}

	public void setQuestionInfoId(Integer questionInfoId) {
		this.questionInfoId = questionInfoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "question_id")
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@Column(name = "question_info_prop", nullable = false, length = 10)
	public String getQuestionInfoProp() {
		return this.questionInfoProp;
	}

	public void setQuestionInfoProp(String questionInfoProp) {
		this.questionInfoProp = questionInfoProp;
	}

	@Column(name = "question_info_value", nullable = false, length = 65535)
	public String getQuestionInfoValue() {
		return this.questionInfoValue;
	}

	public void setQuestionInfoValue(String questionInfoValue) {
		this.questionInfoValue = questionInfoValue;
	}

	@Column(name = "question_info_desc", length = 65535)
	public String getQuestionInfoDesc() {
		return this.questionInfoDesc;
	}

	public void setQuestionInfoDesc(String questionInfoDesc) {
		this.questionInfoDesc = questionInfoDesc;
	}

}
