package com.yuen.domain;
// Generated Jan 30, 2018 8:45:22 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QuestionContentMap generated by hbm2java
 */
@Entity
@Table(name = "question_content_map", catalog = "mycontact")
public class QuestionContentMap implements java.io.Serializable {

	private Integer questionContentMap;
	private CourseContent courseContent;
	private Question question;

	public QuestionContentMap() {
	}

	public QuestionContentMap(CourseContent courseContent, Question question) {
		this.courseContent = courseContent;
		this.question = question;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "question_content_map", unique = true, nullable = false)
	public Integer getQuestionContentMap() {
		return this.questionContentMap;
	}

	public void setQuestionContentMap(Integer questionContentMap) {
		this.questionContentMap = questionContentMap;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "course_content_id")
	public CourseContent getCourseContent() {
		return this.courseContent;
	}

	public void setCourseContent(CourseContent courseContent) {
		this.courseContent = courseContent;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "question_id")
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

}
