package com.yuen.domain;
// Generated Jan 30, 2018 8:45:22 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QuestionAccessMode generated by hbm2java
 */
@Entity
@Table(name = "question_access_mode", catalog = "mycontact")
public class QuestionAccessMode implements java.io.Serializable {

	private QuestionAccessModeId id;
	private Previledge previledge;
	private Question question;
	private User userByGrantorId;
	private User userByAccessorId;
	private Date questionAccessModeValidStartdate;
	private Date questionAccessModeValidEnddate;
	private Date questionAccessModeValidStarttime;
	private Date questionAccessModeValidEndtime;
	private boolean questionAccessModeIsDisabled;
	private String questionAccessModeDesc;

	public QuestionAccessMode() {
	}

	public QuestionAccessMode(QuestionAccessModeId id, User userByGrantorId, Date questionAccessModeValidStartdate,
			Date questionAccessModeValidStarttime, boolean questionAccessModeIsDisabled) {
		this.id = id;
		this.userByGrantorId = userByGrantorId;
		this.questionAccessModeValidStartdate = questionAccessModeValidStartdate;
		this.questionAccessModeValidStarttime = questionAccessModeValidStarttime;
		this.questionAccessModeIsDisabled = questionAccessModeIsDisabled;
	}

	public QuestionAccessMode(QuestionAccessModeId id, Previledge previledge, Question question, User userByGrantorId,
			User userByAccessorId, Date questionAccessModeValidStartdate, Date questionAccessModeValidEnddate,
			Date questionAccessModeValidStarttime, Date questionAccessModeValidEndtime,
			boolean questionAccessModeIsDisabled, String questionAccessModeDesc) {
		this.id = id;
		this.previledge = previledge;
		this.question = question;
		this.userByGrantorId = userByGrantorId;
		this.userByAccessorId = userByAccessorId;
		this.questionAccessModeValidStartdate = questionAccessModeValidStartdate;
		this.questionAccessModeValidEnddate = questionAccessModeValidEnddate;
		this.questionAccessModeValidStarttime = questionAccessModeValidStarttime;
		this.questionAccessModeValidEndtime = questionAccessModeValidEndtime;
		this.questionAccessModeIsDisabled = questionAccessModeIsDisabled;
		this.questionAccessModeDesc = questionAccessModeDesc;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "questionAccessModeId", column = @Column(name = "question_access_mode_id", nullable = false)),
			@AttributeOverride(name = "questionAccessModeGrantedDate", column = @Column(name = "question_access_mode_granted_date", nullable = false, length = 10)) })
	public QuestionAccessModeId getId() {
		return this.id;
	}

	public void setId(QuestionAccessModeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "previledge_id")
	public Previledge getPreviledge() {
		return this.previledge;
	}

	public void setPreviledge(Previledge previledge) {
		this.previledge = previledge;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "question_id")
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "grantor_id", nullable = false)
	public User getUserByGrantorId() {
		return this.userByGrantorId;
	}

	public void setUserByGrantorId(User userByGrantorId) {
		this.userByGrantorId = userByGrantorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "accessor_id")
	public User getUserByAccessorId() {
		return this.userByAccessorId;
	}

	public void setUserByAccessorId(User userByAccessorId) {
		this.userByAccessorId = userByAccessorId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "question_access_mode_valid_startdate", nullable = false, length = 10)
	public Date getQuestionAccessModeValidStartdate() {
		return this.questionAccessModeValidStartdate;
	}

	public void setQuestionAccessModeValidStartdate(Date questionAccessModeValidStartdate) {
		this.questionAccessModeValidStartdate = questionAccessModeValidStartdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "question_access_mode_valid_enddate", length = 10)
	public Date getQuestionAccessModeValidEnddate() {
		return this.questionAccessModeValidEnddate;
	}

	public void setQuestionAccessModeValidEnddate(Date questionAccessModeValidEnddate) {
		this.questionAccessModeValidEnddate = questionAccessModeValidEnddate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "question_access_mode_valid_starttime", nullable = false, length = 8)
	public Date getQuestionAccessModeValidStarttime() {
		return this.questionAccessModeValidStarttime;
	}

	public void setQuestionAccessModeValidStarttime(Date questionAccessModeValidStarttime) {
		this.questionAccessModeValidStarttime = questionAccessModeValidStarttime;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "question_access_mode_valid_endtime", length = 8)
	public Date getQuestionAccessModeValidEndtime() {
		return this.questionAccessModeValidEndtime;
	}

	public void setQuestionAccessModeValidEndtime(Date questionAccessModeValidEndtime) {
		this.questionAccessModeValidEndtime = questionAccessModeValidEndtime;
	}

	@Column(name = "question_access_mode_is_disabled", nullable = false)
	public boolean isQuestionAccessModeIsDisabled() {
		return this.questionAccessModeIsDisabled;
	}

	public void setQuestionAccessModeIsDisabled(boolean questionAccessModeIsDisabled) {
		this.questionAccessModeIsDisabled = questionAccessModeIsDisabled;
	}

	@Column(name = "question_access_mode_desc", length = 65535)
	public String getQuestionAccessModeDesc() {
		return this.questionAccessModeDesc;
	}

	public void setQuestionAccessModeDesc(String questionAccessModeDesc) {
		this.questionAccessModeDesc = questionAccessModeDesc;
	}

}
