package com.yuen.domain;
// Generated Jan 30, 2018 8:45:22 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QuestionTopicMap generated by hbm2java
 */
@Entity
@Table(name = "question_topic_map", catalog = "mycontact")
public class QuestionTopicMap implements java.io.Serializable {

	private Integer questionTopicMap;
	private Question question;
	private Topic topic;

	public QuestionTopicMap() {
	}

	public QuestionTopicMap(Question question, Topic topic) {
		this.question = question;
		this.topic = topic;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "question_topic_map", unique = true, nullable = false)
	public Integer getQuestionTopicMap() {
		return this.questionTopicMap;
	}

	public void setQuestionTopicMap(Integer questionTopicMap) {
		this.questionTopicMap = questionTopicMap;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "question_id", nullable = false)
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "topic_id", nullable = false)
	public Topic getTopic() {
		return this.topic;
	}

	public void setTopic(Topic topic) {
		this.topic = topic;
	}

}
