package com.yuen.domain;
// Generated Jan 30, 2018 8:45:22 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "mycontact")
public class Role implements java.io.Serializable {

	private Integer roleId;
	private String roleCode;
	private String roleDesc;
	private Set<RolePreviledgeMap> rolePreviledgeMaps = new HashSet<RolePreviledgeMap>(0);

	public Role() {
	}

	public Role(String roleCode, String roleDesc) {
		this.roleCode = roleCode;
		this.roleDesc = roleDesc;
	}

	public Role(String roleCode, String roleDesc, Set<RolePreviledgeMap> rolePreviledgeMaps) {
		this.roleCode = roleCode;
		this.roleDesc = roleDesc;
		this.rolePreviledgeMaps = rolePreviledgeMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "role_id", unique = true, nullable = false)
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "role_code", nullable = false, length = 100)
	public String getRoleCode() {
		return this.roleCode;
	}

	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}

	@Column(name = "role_desc", nullable = false, length = 65535)
	public String getRoleDesc() {
		return this.roleDesc;
	}

	public void setRoleDesc(String roleDesc) {
		this.roleDesc = roleDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<RolePreviledgeMap> getRolePreviledgeMaps() {
		return this.rolePreviledgeMaps;
	}

	public void setRolePreviledgeMaps(Set<RolePreviledgeMap> rolePreviledgeMaps) {
		this.rolePreviledgeMaps = rolePreviledgeMaps;
	}

}
