package com.yuen.domain;
// Generated Jan 30, 2018 8:45:22 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TestQuestionMap generated by hbm2java
 */
@Entity
@Table(name = "test_question_map", catalog = "mycontact")
public class TestQuestionMap implements java.io.Serializable {

	private Integer testQuestionMapId;
	private Question questionByEditmodeQuestionId;
	private Question questionByTestmodeQuestionId;
	private TestSection testSection;
	private double testQuestionMapScore;
	private String testQuestionMapDesc;

	public TestQuestionMap() {
	}

	public TestQuestionMap(double testQuestionMapScore) {
		this.testQuestionMapScore = testQuestionMapScore;
	}

	public TestQuestionMap(Question questionByEditmodeQuestionId, Question questionByTestmodeQuestionId,
			TestSection testSection, double testQuestionMapScore, String testQuestionMapDesc) {
		this.questionByEditmodeQuestionId = questionByEditmodeQuestionId;
		this.questionByTestmodeQuestionId = questionByTestmodeQuestionId;
		this.testSection = testSection;
		this.testQuestionMapScore = testQuestionMapScore;
		this.testQuestionMapDesc = testQuestionMapDesc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "test_question_map_id", unique = true, nullable = false)
	public Integer getTestQuestionMapId() {
		return this.testQuestionMapId;
	}

	public void setTestQuestionMapId(Integer testQuestionMapId) {
		this.testQuestionMapId = testQuestionMapId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "editmode_question_id")
	public Question getQuestionByEditmodeQuestionId() {
		return this.questionByEditmodeQuestionId;
	}

	public void setQuestionByEditmodeQuestionId(Question questionByEditmodeQuestionId) {
		this.questionByEditmodeQuestionId = questionByEditmodeQuestionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "testmode_question_id")
	public Question getQuestionByTestmodeQuestionId() {
		return this.questionByTestmodeQuestionId;
	}

	public void setQuestionByTestmodeQuestionId(Question questionByTestmodeQuestionId) {
		this.questionByTestmodeQuestionId = questionByTestmodeQuestionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "test_section_id")
	public TestSection getTestSection() {
		return this.testSection;
	}

	public void setTestSection(TestSection testSection) {
		this.testSection = testSection;
	}

	@Column(name = "test_question_map_score", nullable = false, precision = 22, scale = 0)
	public double getTestQuestionMapScore() {
		return this.testQuestionMapScore;
	}

	public void setTestQuestionMapScore(double testQuestionMapScore) {
		this.testQuestionMapScore = testQuestionMapScore;
	}

	@Column(name = "test_question_map_desc", length = 65535)
	public String getTestQuestionMapDesc() {
		return this.testQuestionMapDesc;
	}

	public void setTestQuestionMapDesc(String testQuestionMapDesc) {
		this.testQuestionMapDesc = testQuestionMapDesc;
	}

}
