package com.yuen.domain;
// Generated Jan 30, 2018 8:45:22 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TestReviewerMap generated by hbm2java
 */
@Entity
@Table(name = "test_reviewer_map", catalog = "mycontact")
public class TestReviewerMap implements java.io.Serializable {

	private Integer testReviewerMapId;
	private User userByUserId;
	private User userByUseUserId;
	private Date testReviewerMapAssigndate;
	private Date testReviewerMapAssigntime;
	private Date testReviewerMapEnddate;
	private Date testReviewerMapEndTime;
	private String testReviewerMapDesc;

	public TestReviewerMap() {
	}

	public TestReviewerMap(Date testReviewerMapAssigndate, Date testReviewerMapAssigntime, Date testReviewerMapEnddate,
			Date testReviewerMapEndTime) {
		this.testReviewerMapAssigndate = testReviewerMapAssigndate;
		this.testReviewerMapAssigntime = testReviewerMapAssigntime;
		this.testReviewerMapEnddate = testReviewerMapEnddate;
		this.testReviewerMapEndTime = testReviewerMapEndTime;
	}

	public TestReviewerMap(User userByUserId, User userByUseUserId, Date testReviewerMapAssigndate,
			Date testReviewerMapAssigntime, Date testReviewerMapEnddate, Date testReviewerMapEndTime,
			String testReviewerMapDesc) {
		this.userByUserId = userByUserId;
		this.userByUseUserId = userByUseUserId;
		this.testReviewerMapAssigndate = testReviewerMapAssigndate;
		this.testReviewerMapAssigntime = testReviewerMapAssigntime;
		this.testReviewerMapEnddate = testReviewerMapEnddate;
		this.testReviewerMapEndTime = testReviewerMapEndTime;
		this.testReviewerMapDesc = testReviewerMapDesc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "test_reviewer_map_id", unique = true, nullable = false)
	public Integer getTestReviewerMapId() {
		return this.testReviewerMapId;
	}

	public void setTestReviewerMapId(Integer testReviewerMapId) {
		this.testReviewerMapId = testReviewerMapId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUserByUserId() {
		return this.userByUserId;
	}

	public void setUserByUserId(User userByUserId) {
		this.userByUserId = userByUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "use_user_id")
	public User getUserByUseUserId() {
		return this.userByUseUserId;
	}

	public void setUserByUseUserId(User userByUseUserId) {
		this.userByUseUserId = userByUseUserId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "test_reviewer_map_assigndate", nullable = false, length = 10)
	public Date getTestReviewerMapAssigndate() {
		return this.testReviewerMapAssigndate;
	}

	public void setTestReviewerMapAssigndate(Date testReviewerMapAssigndate) {
		this.testReviewerMapAssigndate = testReviewerMapAssigndate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "test_reviewer_map_assigntime", nullable = false, length = 8)
	public Date getTestReviewerMapAssigntime() {
		return this.testReviewerMapAssigntime;
	}

	public void setTestReviewerMapAssigntime(Date testReviewerMapAssigntime) {
		this.testReviewerMapAssigntime = testReviewerMapAssigntime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "test_reviewer_map_enddate", nullable = false, length = 10)
	public Date getTestReviewerMapEnddate() {
		return this.testReviewerMapEnddate;
	}

	public void setTestReviewerMapEnddate(Date testReviewerMapEnddate) {
		this.testReviewerMapEnddate = testReviewerMapEnddate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "test_reviewer_map_end_time", nullable = false, length = 8)
	public Date getTestReviewerMapEndTime() {
		return this.testReviewerMapEndTime;
	}

	public void setTestReviewerMapEndTime(Date testReviewerMapEndTime) {
		this.testReviewerMapEndTime = testReviewerMapEndTime;
	}

	@Column(name = "test_reviewer_map_desc", length = 65535)
	public String getTestReviewerMapDesc() {
		return this.testReviewerMapDesc;
	}

	public void setTestReviewerMapDesc(String testReviewerMapDesc) {
		this.testReviewerMapDesc = testReviewerMapDesc;
	}

}
