package com.yuen.domain;
// Generated Jan 30, 2018 8:45:22 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UnivMission generated by hbm2java
 */
@Entity
@Table(name = "univ_mission", catalog = "mycontact")
public class UnivMission implements java.io.Serializable {

	private Integer missionId;
	private UnivMissionVersion univMissionVersion;
	private String missionCode;
	private String missionDescVn;
	private String missionDescEn;
	private Set<MissionPeoMap> missionPeoMaps = new HashSet<MissionPeoMap>(0);

	public UnivMission() {
	}

	public UnivMission(String missionCode, String missionDescVn, String missionDescEn) {
		this.missionCode = missionCode;
		this.missionDescVn = missionDescVn;
		this.missionDescEn = missionDescEn;
	}

	public UnivMission(UnivMissionVersion univMissionVersion, String missionCode, String missionDescVn,
			String missionDescEn, Set<MissionPeoMap> missionPeoMaps) {
		this.univMissionVersion = univMissionVersion;
		this.missionCode = missionCode;
		this.missionDescVn = missionDescVn;
		this.missionDescEn = missionDescEn;
		this.missionPeoMaps = missionPeoMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "mission_id", unique = true, nullable = false)
	public Integer getMissionId() {
		return this.missionId;
	}

	public void setMissionId(Integer missionId) {
		this.missionId = missionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "univ_mission_version_id")
	public UnivMissionVersion getUnivMissionVersion() {
		return this.univMissionVersion;
	}

	public void setUnivMissionVersion(UnivMissionVersion univMissionVersion) {
		this.univMissionVersion = univMissionVersion;
	}

	@Column(name = "mission_code", nullable = false, length = 5)
	public String getMissionCode() {
		return this.missionCode;
	}

	public void setMissionCode(String missionCode) {
		this.missionCode = missionCode;
	}

	@Column(name = "mission_desc_vn", nullable = false, length = 65535)
	public String getMissionDescVn() {
		return this.missionDescVn;
	}

	public void setMissionDescVn(String missionDescVn) {
		this.missionDescVn = missionDescVn;
	}

	@Column(name = "mission_desc_en", nullable = false, length = 65535)
	public String getMissionDescEn() {
		return this.missionDescEn;
	}

	public void setMissionDescEn(String missionDescEn) {
		this.missionDescEn = missionDescEn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "univMission")
	public Set<MissionPeoMap> getMissionPeoMaps() {
		return this.missionPeoMaps;
	}

	public void setMissionPeoMaps(Set<MissionPeoMap> missionPeoMaps) {
		this.missionPeoMaps = missionPeoMaps;
	}

}
